services:
  tagworker:
    build: .
    container_name: tagworker
    volumes:
      - /mnt/data/torrents:/data/torrents

      - /home/downloaduser/tagWorker/config:/app/config
      - /home/downloaduser/tagWorker/logs:/app/logs
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - LOGLEVEL=${LOGLEVEL:-INFO}
    restart: unless-stopped
